# Generated by Django 4.1.5 on 2023-02-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_listened_alter_song_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='song',
            name='listened',
            field=models.BigIntegerField(default=0),
        ),
    ]
